name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Replace Function Key placeholder
        run: |
          if [ -n "${{ secrets.AZURE_FUNCTION_KEY }}" ]; then
            echo "Function key found. Replacing placeholder..."
            sed -i 's/<FUNCTION_KEY_PLACEHOLDER>/'"${{secrets.AZURE_FUNCTION_KEY}}"'/g' src/environments/environment.prod.ts
          else
            echo "No function key found. Skipping placeholder replacement."
          fi

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_FLOWER_03A3B6A0}}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"         # App source code path (if your Angular app is at the repo root)
          api_location: ""          # Leave blank if no API code in the repo
          output_location: "dist/angular-pro1"  # Adjust to match your angular.json outputPath


  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_FLOWER_03A3B6A0}}
          action: "close"
